# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: | 
    dotnet restore LoanToDecisionEngine.sln
    ls
  displayName: 'dotnet restore'


- script: | 
    dotnet build LoanToDecisionEngine.sln
    ls
    cd /home/vsts/work/1/s/LoanToDecisionEngine/bin/Debug/netcoreapp2.1/
    ls -al
    pwd
  displayName: 'dotnet build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '/home/vsts/work/1/s/LoanToDecisionEngine/bin/Debug/netcoreapp2.1/'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    
- task: LambdaNETCoreDeploy@1
  inputs:
    awsCredentials: 'awsconnection'
    regionName: 'ap-south-1'
    command: 'deployFunction'
    packageOnly: false
    lambdaProjectPath: './LoanToDecisionEngine'
    functionName: 'LoanToDecisionEngine'
    functionRole: 'LoanToDecisionEngine-role-ldszk1c6'
    functionHandler: 'LoanToDecisionEngine::LoanToDecisionEngine.Function::FunctionHandler'
    functionMemory: 512
    functionTimeout: 60
